services:
  - type: web
    name: medlit-ai-bot
    runtime: python
    pythonVersion: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8233772963:AAHHu9X00Y22A75eVjXOs7m0Aw23g3aCin8
